version: 2
jobs:

  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: apk --no-cache add git
      - run: ./build.sh fpm-alpine --git-hash

  push:
    docker:
      - image: docker

    steps:
      - checkout
      - setup_remote_docker
      - run: 'echo "TAG: $CIRCLE_TAG"'
      - run: apk --no-cache add git
      - run: ./build.sh fpm-alpine --git-hash
      - run: './build.sh $(echo $CIRCLE_TAG | grep -Eo "^[a-z]+(\-[a-z]+)*") $(echo $CIRCLE_TAG | grep -Eo "[0-9]+\.[0-9]+(\-(alpha|beta)\d+?)?$") --push'

workflows:
  version: 2
  build:
    jobs:
      - build
      - push:
          filter:
            tags:
              # only: /^[a-z]+(\-[a-z]+)*\-\d+\.\d+(\-(alpha|beta)\d+)?$/
              only: /^.*$/
